#!/usr/bin/env bash
# Margine image build — section: 20-flatpaks
# Sub-script of the build.sh orchestrator. Decomposed on 2026-06-06
# (audit §8 rec #22 — split build.sh into per-area install scripts).
# See build_files/00-common.sh + build_files/build.sh.
set -euo pipefail
. /ctx/00-common.sh

# 1. Margine default Flatpak apps — two-stage delivery (PR D, 2026-06-04)
# ---------------------------------------------------------------------------
# As of PR D ("hybrid bake + defer Flatpaks") Margine ships its default
# apps in TWO buckets:
#
#   BAKE (kickstart %post --nochroot at install time, ~22 apps):
#     Browser, mail, password, office, image+pdf+video viewer,
#     GNOME productivity suite. Apps the user expects to find ALREADY
#     INSTALLED on the desktop the first time they log in. Anaconda
#     does `flatpak install --system` into the installer env's
#     /var/lib/flatpak, then rsyncs that dir into the target's
#     /var/lib/flatpak. Cost: +5-10 min Anaconda install time (user
#     sees "Running post-install scripts..."), 0 GB extra ISO.
#     Pattern: Bazzite installer/system_files/.../install-flatpaks.ks.
#
#   DEFER (.preinstall files + flatpak-preinstall.service at first
#   boot, ~12 apps):
#     Heavy creative apps (GIMP, Inkscape, darktable, OBS, Reaper,
#     ...) the user doesn't need in the first 10 min after first
#     login. flatpak-preinstall.service downloads them in background.
#     Pattern: upstream Flatpak preinstall.d API.
#
# Lists are kept here and copied at build time into:
#   /usr/share/margine/installer-flatpaks-base
#       — read by disk_config/iso-gnome.toml kickstart %post --nochroot.
#   /usr/share/flatpak/preinstall.d/margine-defaults.preinstall
#       — read by flatpak-preinstall.service on first boot.
#
# VS Code is intentionally NOT in either list: Bluefin DX already
# preinstalls VS Code from the Microsoft repo with dev container
# tooling already wired up.
#
# The gaming variant adds its own bake list
# (build_files/gaming/install.sh writes
# /usr/share/margine/installer-flatpaks-gaming) and its own defer
# list (build_files/gaming/margine-gaming.preinstall).

# ---- BAKE list (instant at first boot) ----
# Source of truth: installer/flatpaks-base, accessible from this script
# at /ctx/installer-flatpaks-base via the ctx layer (Containerfile).
# That same file is consumed at ISO build time by installer/build.sh,
# so a single edit propagates to BOTH the OCI image manifest and the
# installer-rootfs that the Anaconda kickstart rsyncs. Audit §3.5.
log "Installing /usr/share/margine/installer-flatpaks-base from /ctx/installer-flatpaks-base"
mkdir -p /usr/share/margine
cp /ctx/installer-flatpaks-base /usr/share/margine/installer-flatpaks-base
chmod 0644 /usr/share/margine/installer-flatpaks-base
log "BAKE list — $(grep -cv '^#\|^$' /usr/share/margine/installer-flatpaks-base) apps:"
grep -v '^#\|^$' /usr/share/margine/installer-flatpaks-base | sed 's/^/  /'

# ---- DEFER list (first-boot flatpak-preinstall.service) ----
# Belt + suspenders (2026-06-04): every BAKE app is ALSO in the DEFER
# list. If the kickstart-time BAKE silently fails (verified failure
# scenario: installer-env /var tmpfs OOM, network blip during install,
# silent flatpak error), flatpak-preinstall.service at first boot
# catches them — 5-15 min wait instead of instant, but never "apps
# missing". flatpak skips already-installed entries silently, so on
# a successful BAKE the DEFER preinstall is a no-op.
log "Writing /usr/share/flatpak/preinstall.d/margine-defaults.preinstall (DEFER + BAKE-fallback)"

# Bluefin DX uses the upstream Flatpak `preinstall` API (introduced in
# Flatpak 1.16): /usr/share/flatpak/preinstall.d/*.preinstall files
# are read by `flatpak-preinstall.service` at boot. The older uBlue
# /etc/ublue-os/system-flatpaks.list mechanism is NO LONGER honored
# on current Bluefin DX — files there are silently ignored.
mkdir -p /usr/share/flatpak/preinstall.d
{
  echo "# Margine apps installed via flatpak-preinstall.service at"
  echo "# first boot. Two categories merged in one file:"
  echo "#"
  echo "#   1. DEFER apps (heavy creative — GIMP, Inkscape, darktable,"
  echo "#      OBS) — these have no other install path, always 5-15 min"
  echo "#      first-boot wait."
  echo "#"
  echo "#   2. BAKE apps (browser, mail, office, GNOME suite) — these"
  echo "#      are ALSO in /usr/share/margine/installer-flatpaks-base"
  echo "#      and SHOULD be installed at Anaconda %post time. They"
  echo "#      are listed here too as belt+suspenders: if BAKE silently"
  echo "#      failed, flatpak-preinstall catches them at first boot."
  echo "#      On a successful BAKE this preinstall entry is a no-op"
  echo "#      (flatpak skips already-installed)."
  echo "#"
  echo "# Generated by build.sh; do not edit by hand."
  echo
  for app in \
      org.gimp.GIMP \
      org.inkscape.Inkscape \
      org.darktable.Darktable \
      com.obsproject.Studio \
      app.zen_browser.zen \
      org.mozilla.thunderbird_esr \
      com.bitwarden.desktop \
      org.libreoffice.LibreOffice \
      com.mattjakeman.ExtensionManager \
      org.gnome.Snapshot \
      org.gnome.Showtime \
      org.gnome.Papers \
      org.gnome.Loupe \
      org.gnome.SoundRecorder \
      org.gnome.Calculator \
      org.gnome.Calendar \
      org.gnome.clocks \
      org.gnome.Contacts \
      org.gnome.Weather \
      org.gnome.Maps \
      org.gnome.TextEditor \
      org.gnome.baobab \
      org.gnome.Characters \
      org.gnome.Logs \
      org.gnome.font-viewer \
      org.gnome.gitlab.somas.Apostrophe \
      com.github.PintaProject.Pinta \
      org.audacityteam.Audacity \
      com.github.wwmm.easyeffects \
      fm.reaper.Reaper \
      com.github.neithern.g4music \
      com.rafaelmardojai.Blanket \
      de.haeckerfelix.Fragments ; do
    # Only the "macigni" (~500-700 MB Flatpak each + heavy runtimes)
    # are deferred to flatpak-preinstall.service first-boot. They take
    # 5-10 min to download but the user gets a notification (PR E
    # /usr/libexec/margine-first-boot-status). Everything lighter
    # was moved to the BAKE bucket (kickstart-installed, available
    # at first login) by the 2026-06-04 "more apps in BAKE" rebalance:
    #
    #   moved BAKE: Pinta, Audacity, EasyEffects, Reaper, g4music,
    #               Blanket, Fragments (sum ~420 MB additional in
    #               kickstart download)
    #   kept DEFER: GIMP, Inkscape, darktable, OBS Studio (the four
    #               creative-pro macigni totaling ~2 GB).
    #
    # See /usr/share/margine/installer-flatpaks-base for the full
    # BAKE list (29 base apps after the rebalance).
    echo "[Flatpak Preinstall $app]"
    echo "Branch=stable"
    echo "IsRuntime=false"
    echo
  done
} > /usr/share/flatpak/preinstall.d/margine-defaults.preinstall
chmod 0644 /usr/share/flatpak/preinstall.d/margine-defaults.preinstall

log "margine-defaults.preinstall now:"
cat /usr/share/flatpak/preinstall.d/margine-defaults.preinstall

# Drop the legacy uBlue file if it exists (left behind by older builds
# or by Bluefin DX itself if it still has one). Prevents confusion.
rm -f /etc/ublue-os/system-flatpaks.list

# ---------------------------------------------------------------------------
